import { defineDict } from '@/i18n';

/** Strings for the CMS product list + product editor (ME / SQ / EN). */
export const pd = defineDict({
  me: {
    // list
    title: 'Proizvodi',
    subtitle: 'Katalog, cijene i zalihe na jednom mjestu — sve promjene su odmah vidljive na sajtu.',
    newProduct: 'Novi proizvod',
    searchPh: 'Pretraži po nazivu ili šifri…',
    allCategories: 'Sve kategorije',
    st_all: 'Svi',
    st_active: 'Aktivni',
    st_draft: 'Nacrti',
    stock_all: 'Sve zalihe',
    stock_low: 'Malo na stanju (≤ 5)',
    stock_mto: 'Po narudžbi',
    sort_newest: 'Najnovije prvo',
    sort_name: 'Naziv A–Ž',
    sort_price: 'Cijena',
    sort_stock: 'Zalihe',
    sort_sold: 'Najprodavanije',
    col_product: 'Proizvod',
    col_category: 'Kategorija',
    col_price: 'Cijena',
    col_stock: 'Zalihe',
    col_status: 'Status',
    col_badges: 'Oznake',
    madeToOrder: 'Po narudžbi',
    outOfStock: 'Nema na stanju',
    soldN: 'Prodato: {n}',
    active: 'Aktivan',
    draft: 'Nacrt',
    onRequest: 'Na upit',
    featured: 'Istaknut',
    noCategory: 'Bez kategorije',
    edit: 'Uredi',
    duplicate: 'Dupliraj',
    viewOnSite: 'Pogledaj na sajtu',
    delete: 'Obriši',
    moreActions: 'Više akcija',
    duplicated: 'Kopija je kreirana kao nacrt',
    deleteTitle: 'Obrisati „{name}“?',
    deleteText: 'Proizvod će biti uklonjen iz kataloga i sa sajta. Ova radnja se ne može poništiti.',
    deleted: 'Proizvod je obrisan',
    nowActive: '„{name}“ je sada aktivan na sajtu',
    nowDraft: '„{name}“ je prebačen u nacrt',
    selectedN: 'Izabrano: {n}',
    selected: 'izabrano',
    selectAll: 'Izaberi sve',
    selectRow: 'Izaberi proizvod',
    clearSelection: 'Poništi izbor',
    bulkActivate: 'Aktiviraj',
    bulkDeactivate: 'Deaktiviraj',
    bulkActivated: 'Aktivirani proizvodi: {n}',
    bulkDeactivated: 'Proizvodi prebačeni u nacrt: {n}',
    bulkDeleteTitle: 'Obrisati izabrane proizvode ({n})?',
    bulkDeleted: 'Obrisani proizvodi: {n}',
    emptyTitle: 'Nema proizvoda za zadate filtere',
    emptyText: 'Promijenite pretragu ili očistite filtere da vidite cijeli katalog.',
    clearFilters: 'Očisti filtere',
    showing: 'Prikazano {n} od {total}',
    lowStock: 'Malo zaliha',
    packsUnit: 'pak.',
    sortBy: 'Sortiranje',
    emptyCatalogTitle: 'Katalog je još prazan',
    emptyCatalogText: 'Dodajte prvi proizvod — sa cijenom i slikama pojavljuje se na sajtu čim ga sačuvate.',

    // editor
    newTitle: 'Novi proizvod',
    newDesc: 'Unesite naziv, cijenu i slike — aktivan proizvod se pojavljuje na sajtu čim ga sačuvate.',
    createdOn: 'Kreirano {date}',
    updatedAgo: 'ažurirano {ago}',
    save: 'Sačuvaj',
    c_basic: 'Osnovno',
    c_basic_d: 'Naziv i opisi na tri jezika — tačkica na jeziku označava prevod koji nedostaje.',
    f_name: 'Naziv proizvoda',
    f_short: 'Kratak opis',
    f_short_h: 'Jedna rečenica ispod naziva na stranici proizvoda.',
    f_desc: 'Opis',
    f_desc_h: 'Detaljan opis materijala, ugradnje i održavanja.',
    c_images: 'Slike',
    c_images_d: 'Prva slika je naslovna. Prevucite slike da promijenite redoslijed.',
    c_pricing: 'Cijene',
    c_pricing_d: 'Sve cijene su sa uračunatim PDV-om.',
    f_price: 'Redovna cijena',
    f_sale: 'Akcijska cijena',
    f_sale_h: 'Ostavite prazno ako proizvod nije na akciji.',
    f_unit: 'Jedinica prodaje',
    f_pack: 'm² u paketu',
    f_pack_h: 'Kupac naručuje cijele pakete.',
    unit_kom: 'Komad (kom)',
    unit_m2: 'Kvadratni metar (m²)',
    unit_m: 'Dužni metar (m)',
    unit_set: 'Set / komplet',
    discountHint: 'Popust {pct}% — kupac štedi {amount}',
    saleTooHigh: 'Akcijska cijena mora biti niža od redovne da bi se prikazala.',
    packHint: 'Paket od {size} m² košta {price}',
    regularOnly: 'Bez akcije — kupac plaća redovnu cijenu.',
    c_options: 'Opcije / varijante',
    c_options_d: 'Dimenzije, boje i izvedbe između kojih kupac bira.',
    addOption: 'Dodaj opciju',
    addValue: 'Dodaj vrijednost',
    optionName: 'Naziv opcije',
    type_swatch: 'Boje',
    type_button: 'Dugmad',
    valueLabel: 'Vrijednost',
    priceDelta: 'Doplata',
    noOptions: 'Bez opcija — proizvod se prodaje u jednoj izvedbi.',
    quickAdd: 'Brzo dodaj',
    moveUp: 'Pomjeri gore',
    moveDown: 'Pomjeri dolje',
    remove: 'Ukloni',
    pickColor: 'Izaberi boju',
    langHint: 'Jezik unosa',
    c_specs: 'Specifikacije',
    c_specs_d: 'Tehnički podaci u tabeli na stranici proizvoda.',
    specLabel: 'Svojstvo',
    specValue: 'Vrijednost',
    addSpec: 'Dodaj red',
    noSpecs: 'Još nema specifikacija — dodajte materijal, dimenzije ili garanciju.',
    c_seo: 'SEO',
    c_seo_d: 'Kako se proizvod prikazuje u Google pretrazi.',
    f_slug: 'URL adresa',
    slugAuto: 'Generiše se automatski iz crnogorskog naziva.',
    slugManual: 'Ručno uređena adresa.',
    slugReset: 'Vrati automatsku',
    f_metaTitle: 'Meta naslov',
    f_metaTitle_h: 'Prazno = naziv proizvoda.',
    f_metaDesc: 'Meta opis',
    f_metaDesc_h: 'Prazno = kratak opis.',
    googlePreview: 'Pregled u pretrazi',
    inStock: 'Na stanju',
    c_status: 'Status',
    statusActiveH: 'Vidljiv na sajtu i dostupan za naručivanje.',
    statusDraftH: 'Sakriven sa sajta dok ga ne aktivirate.',
    f_active: 'Aktivan na sajtu',
    f_featured: 'Istaknut proizvod',
    f_featured_h: 'Prikazuje se u izdvojenim sekcijama na početnoj.',
    translations: 'Prevodi',
    c_org: 'Organizacija',
    f_category: 'Kategorija',
    chooseCategory: 'Izaberite kategoriju…',
    f_badges: 'Oznake na kartici',
    f_quote: 'Cijena po mjeri / na upit',
    f_quote_h: 'Umjesto „Dodaj u korpu“ kupac traži ponudu.',
    c_stock: 'Zalihe',
    f_sku: 'Šifra (SKU)',
    f_stock: 'Količina na stanju',
    f_mto: 'Po narudžbi',
    f_mto_h: 'Izrađuje se po narudžbi — zalihe se ne prate.',
    lowStockWarn: 'Malo na stanju — vrijeme je za dopunu.',
    outOfStockWarn: 'Nema na stanju — na sajtu se prikazuje kao „po narudžbi“.',
    stockPacksH: 'Za m² proizvode zalihe se vode u paketima.',
    c_install: 'Ugradnja',
    f_install: 'Nudimo ugradnju',
    f_install_h: 'Kupac može dodati ugradnju u korpi.',
    f_installPrice: 'Cijena ugradnje',
    c_delivery: 'Isporuka i garancija',
    f_lead: 'Rok isporuke',
    daysUnit: 'dana',
    f_warranty: 'Garancija',
    yearsUnit: 'god.',
    c_preview: 'Pregled na sajtu',
    c_preview_d: 'Kartica se mijenja dok kucate.',
    shortcutTip: 'Savjet: Ctrl + S čuva promjene.',
    e_name: 'Unesite naziv na crnogorskom.',
    e_price: 'Cijena mora biti veća od 0.',
    e_category: 'Izaberite kategoriju.',
    fixErrors: 'Provjerite označena polja',
    created: 'Proizvod je kreiran',
    saved: 'Promjene su sačuvane',
    notFound: 'Proizvod nije pronađen',
    notFoundText: 'Možda je obrisan ili link nije ispravan.',
    backToList: 'Nazad na proizvode',
    leaveTitle: 'Napustiti bez čuvanja?',
    leaveText: 'Nesačuvane promjene na ovom proizvodu biće izgubljene.',
    leave: 'Napusti',
  },
  sq: {
    title: 'Produktet',
    subtitle: 'Katalogu, çmimet dhe stoqet në një vend — çdo ndryshim shfaqet menjëherë në faqe.',
    newProduct: 'Produkt i ri',
    searchPh: 'Kërko sipas emrit ose kodit…',
    allCategories: 'Të gjitha kategoritë',
    st_all: 'Të gjitha',
    st_active: 'Aktive',
    st_draft: 'Drafte',
    stock_all: 'Të gjitha stoqet',
    stock_low: 'Stok i ulët (≤ 5)',
    stock_mto: 'Me porosi',
    sort_newest: 'Më të rejat',
    sort_name: 'Emri A–Zh',
    sort_price: 'Çmimi',
    sort_stock: 'Stoku',
    sort_sold: 'Më të shiturat',
    col_product: 'Produkti',
    col_category: 'Kategoria',
    col_price: 'Çmimi',
    col_stock: 'Stoku',
    col_status: 'Statusi',
    col_badges: 'Etiketat',
    madeToOrder: 'Me porosi',
    outOfStock: 'Pa stok',
    soldN: 'Shitur: {n}',
    active: 'Aktiv',
    draft: 'Draft',
    onRequest: 'Me kërkesë',
    featured: 'I veçuar',
    noCategory: 'Pa kategori',
    edit: 'Ndrysho',
    duplicate: 'Dupliko',
    viewOnSite: 'Shiko në faqe',
    delete: 'Fshij',
    moreActions: 'Më shumë veprime',
    duplicated: 'Kopja u krijua si draft',
    deleteTitle: 'Të fshihet „{name}“?',
    deleteText: 'Produkti do të hiqet nga katalogu dhe nga faqja. Ky veprim nuk mund të zhbëhet.',
    deleted: 'Produkti u fshi',
    nowActive: '„{name}“ tani është aktiv në faqe',
    nowDraft: '„{name}“ u kalua në draft',
    selectedN: 'Të zgjedhur: {n}',
    selected: 'të zgjedhur',
    selectAll: 'Zgjidh të gjitha',
    selectRow: 'Zgjidh produktin',
    clearSelection: 'Anulo zgjedhjen',
    bulkActivate: 'Aktivizo',
    bulkDeactivate: 'Çaktivizo',
    bulkActivated: 'Produkte të aktivizuara: {n}',
    bulkDeactivated: 'Produkte të kaluara në draft: {n}',
    bulkDeleteTitle: 'Të fshihen produktet e zgjedhura ({n})?',
    bulkDeleted: 'Produkte të fshira: {n}',
    emptyTitle: 'Asnjë produkt për këto filtra',
    emptyText: 'Ndryshoni kërkimin ose pastroni filtrat për të parë gjithë katalogun.',
    clearFilters: 'Pastro filtrat',
    showing: 'Shfaqen {n} nga {total}',
    lowStock: 'Stok i ulët',
    packsUnit: 'pako',
    sortBy: 'Renditja',
    emptyCatalogTitle: 'Katalogu është ende bosh',
    emptyCatalogText: 'Shtoni produktin e parë — me çmim dhe imazhe shfaqet në faqe sapo ta ruani.',

    newTitle: 'Produkt i ri',
    newDesc: 'Shkruani emrin, çmimin dhe imazhet — produkti aktiv shfaqet në faqe sapo ta ruani.',
    createdOn: 'Krijuar më {date}',
    updatedAgo: 'përditësuar {ago}',
    save: 'Ruaj',
    c_basic: 'Të dhënat bazë',
    c_basic_d: 'Emri dhe përshkrimet në tre gjuhë — pika te gjuha tregon përkthimin që mungon.',
    f_name: 'Emri i produktit',
    f_short: 'Përshkrim i shkurtër',
    f_short_h: 'Një fjali nën emrin në faqen e produktit.',
    f_desc: 'Përshkrimi',
    f_desc_h: 'Përshkrim i detajuar i materialeve, montimit dhe mirëmbajtjes.',
    c_images: 'Imazhet',
    c_images_d: 'Imazhi i parë është kopertina. Tërhiqni imazhet për të ndryshuar renditjen.',
    c_pricing: 'Çmimet',
    c_pricing_d: 'Të gjitha çmimet përfshijnë TVSH-në.',
    f_price: 'Çmimi i rregullt',
    f_sale: 'Çmimi në aksion',
    f_sale_h: 'Lëreni bosh nëse produkti nuk është në aksion.',
    f_unit: 'Njësia e shitjes',
    f_pack: 'm² në pako',
    f_pack_h: 'Klienti porosit pako të plota.',
    unit_kom: 'Copë',
    unit_m2: 'Metër katror (m²)',
    unit_m: 'Metër linear (m)',
    unit_set: 'Set / komplet',
    discountHint: 'Zbritje {pct}% — klienti kursen {amount}',
    saleTooHigh: 'Çmimi në aksion duhet të jetë më i ulët se i rregullti që të shfaqet.',
    packHint: 'Pakoja prej {size} m² kushton {price}',
    regularOnly: 'Pa aksion — klienti paguan çmimin e rregullt.',
    c_options: 'Opsionet / variantet',
    c_options_d: 'Dimensionet, ngjyrat dhe versionet që zgjedh klienti.',
    addOption: 'Shto opsion',
    addValue: 'Shto vlerë',
    optionName: 'Emri i opsionit',
    type_swatch: 'Ngjyra',
    type_button: 'Butona',
    valueLabel: 'Vlera',
    priceDelta: 'Shtesë',
    noOptions: 'Pa opsione — produkti shitet në një version të vetëm.',
    quickAdd: 'Shto shpejt',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    remove: 'Hiq',
    pickColor: 'Zgjidh ngjyrën',
    langHint: 'Gjuha e shkrimit',
    c_specs: 'Specifikimet',
    c_specs_d: 'Të dhënat teknike në tabelën e faqes së produktit.',
    specLabel: 'Vetia',
    specValue: 'Vlera',
    addSpec: 'Shto rresht',
    noSpecs: 'Ende nuk ka specifikime — shtoni materialin, dimensionet ose garancinë.',
    c_seo: 'SEO',
    c_seo_d: 'Si shfaqet produkti në kërkimin e Google.',
    f_slug: 'Adresa URL',
    slugAuto: 'Krijohet automatikisht nga emri në malazezisht.',
    slugManual: 'Adresë e ndryshuar manualisht.',
    slugReset: 'Rikthe adresën automatike',
    f_metaTitle: 'Titulli meta',
    f_metaTitle_h: 'Bosh = emri i produktit.',
    f_metaDesc: 'Përshkrimi meta',
    f_metaDesc_h: 'Bosh = përshkrimi i shkurtër.',
    googlePreview: 'Parapamja në kërkim',
    inStock: 'Në stok',
    c_status: 'Statusi',
    statusActiveH: 'I dukshëm në faqe dhe i disponueshëm për porosi.',
    statusDraftH: 'I fshehur nga faqja derisa ta aktivizoni.',
    f_active: 'Aktiv në faqe',
    f_featured: 'Produkt i veçuar',
    f_featured_h: 'Shfaqet në seksionet e veçuara të faqes kryesore.',
    translations: 'Përkthimet',
    c_org: 'Organizimi',
    f_category: 'Kategoria',
    chooseCategory: 'Zgjidhni kategorinë…',
    f_badges: 'Etiketat në kartë',
    f_quote: 'Çmim sipas masës / me kërkesë',
    f_quote_h: 'Në vend të „Shto në shportë“ klienti kërkon ofertë.',
    c_stock: 'Stoku',
    f_sku: 'Kodi (SKU)',
    f_stock: 'Sasia në stok',
    f_mto: 'Me porosi',
    f_mto_h: 'Prodhohet me porosi — stoku nuk ndiqet.',
    lowStockWarn: 'Stok i ulët — është koha për rimbushje.',
    outOfStockWarn: 'Pa stok — në faqe shfaqet si „me porosi“.',
    stockPacksH: 'Për produktet në m² stoku mbahet në pako.',
    c_install: 'Montimi',
    f_install: 'Ofrojmë montim',
    f_install_h: 'Klienti mund ta shtojë montimin në shportë.',
    f_installPrice: 'Çmimi i montimit',
    c_delivery: 'Dorëzimi dhe garancia',
    f_lead: 'Afati i dorëzimit',
    daysUnit: 'ditë',
    f_warranty: 'Garancia',
    yearsUnit: 'vjet',
    c_preview: 'Parapamja në faqe',
    c_preview_d: 'Karta ndryshon ndërsa shkruani.',
    shortcutTip: 'Këshillë: Ctrl + S ruan ndryshimet.',
    e_name: 'Shkruani emrin në malazezisht.',
    e_price: 'Çmimi duhet të jetë më i madh se 0.',
    e_category: 'Zgjidhni kategorinë.',
    fixErrors: 'Kontrolloni fushat e shënuara',
    created: 'Produkti u krijua',
    saved: 'Ndryshimet u ruajtën',
    notFound: 'Produkti nuk u gjet',
    notFoundText: 'Mund të jetë fshirë ose lidhja nuk është e saktë.',
    backToList: 'Kthehu te produktet',
    leaveTitle: 'Të dilet pa ruajtur?',
    leaveText: 'Ndryshimet e paruajtura në këtë produkt do të humbasin.',
    leave: 'Dil',
  },
  en: {
    title: 'Products',
    subtitle: 'Catalogue, prices and stock in one place — every change goes live on the website instantly.',
    newProduct: 'New product',
    searchPh: 'Search by name or SKU…',
    allCategories: 'All categories',
    st_all: 'All',
    st_active: 'Active',
    st_draft: 'Drafts',
    stock_all: 'Any stock',
    stock_low: 'Low stock (≤ 5)',
    stock_mto: 'Made to order',
    sort_newest: 'Newest first',
    sort_name: 'Name A–Z',
    sort_price: 'Price',
    sort_stock: 'Stock',
    sort_sold: 'Bestselling',
    col_product: 'Product',
    col_category: 'Category',
    col_price: 'Price',
    col_stock: 'Stock',
    col_status: 'Status',
    col_badges: 'Badges',
    madeToOrder: 'Made to order',
    outOfStock: 'Out of stock',
    soldN: 'Sold: {n}',
    active: 'Active',
    draft: 'Draft',
    onRequest: 'On request',
    featured: 'Featured',
    noCategory: 'Uncategorised',
    edit: 'Edit',
    duplicate: 'Duplicate',
    viewOnSite: 'View on site',
    delete: 'Delete',
    moreActions: 'More actions',
    duplicated: 'Copy created as a draft',
    deleteTitle: 'Delete “{name}”?',
    deleteText: 'The product will be removed from the catalogue and the website. This cannot be undone.',
    deleted: 'Product deleted',
    nowActive: '“{name}” is now live on the site',
    nowDraft: '“{name}” moved to drafts',
    selectedN: '{n} selected',
    selected: 'selected',
    selectAll: 'Select all',
    selectRow: 'Select product',
    clearSelection: 'Clear selection',
    bulkActivate: 'Activate',
    bulkDeactivate: 'Deactivate',
    bulkActivated: 'Products activated: {n}',
    bulkDeactivated: 'Products moved to drafts: {n}',
    bulkDeleteTitle: 'Delete the selected products ({n})?',
    bulkDeleted: 'Products deleted: {n}',
    emptyTitle: 'No products match these filters',
    emptyText: 'Change the search or clear the filters to see the full catalogue.',
    clearFilters: 'Clear filters',
    showing: 'Showing {n} of {total}',
    lowStock: 'Low stock',
    packsUnit: 'packs',
    sortBy: 'Sort by',
    emptyCatalogTitle: 'The catalogue is still empty',
    emptyCatalogText: 'Add your first product — with a price and images it appears on the website as soon as you save it.',

    newTitle: 'New product',
    newDesc: 'Add a name, price and images — an active product appears on the website as soon as you save it.',
    createdOn: 'Created {date}',
    updatedAgo: 'updated {ago}',
    save: 'Save',
    c_basic: 'Basics',
    c_basic_d: 'Name and descriptions in three languages — a dot on a language marks a missing translation.',
    f_name: 'Product name',
    f_short: 'Short description',
    f_short_h: 'One sentence below the name on the product page.',
    f_desc: 'Description',
    f_desc_h: 'Detailed description of materials, installation and care.',
    c_images: 'Images',
    c_images_d: 'The first image is the cover. Drag images to reorder them.',
    c_pricing: 'Pricing',
    c_pricing_d: 'All prices include VAT.',
    f_price: 'Regular price',
    f_sale: 'Sale price',
    f_sale_h: 'Leave empty if the product is not on sale.',
    f_unit: 'Sold per',
    f_pack: 'm² per pack',
    f_pack_h: 'Customers order whole packs.',
    unit_kom: 'Piece (pc)',
    unit_m2: 'Square metre (m²)',
    unit_m: 'Linear metre (m)',
    unit_set: 'Set',
    discountHint: '{pct}% off — the customer saves {amount}',
    saleTooHigh: 'The sale price must be lower than the regular price to show.',
    packHint: 'A {size} m² pack costs {price}',
    regularOnly: 'Not on sale — customers pay the regular price.',
    c_options: 'Options / variants',
    c_options_d: 'Sizes, colours and versions the customer can choose from.',
    addOption: 'Add option',
    addValue: 'Add value',
    optionName: 'Option name',
    type_swatch: 'Swatches',
    type_button: 'Buttons',
    valueLabel: 'Value',
    priceDelta: 'Surcharge',
    noOptions: 'No options — the product is sold in a single version.',
    quickAdd: 'Quick add',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    pickColor: 'Pick colour',
    langHint: 'Editing language',
    c_specs: 'Specifications',
    c_specs_d: 'Technical data shown in the table on the product page.',
    specLabel: 'Property',
    specValue: 'Value',
    addSpec: 'Add row',
    noSpecs: 'No specifications yet — add material, dimensions or warranty.',
    c_seo: 'SEO',
    c_seo_d: 'How the product appears in Google search.',
    f_slug: 'URL handle',
    slugAuto: 'Generated automatically from the Montenegrin name.',
    slugManual: 'Edited manually.',
    slugReset: 'Reset to automatic',
    f_metaTitle: 'Meta title',
    f_metaTitle_h: 'Empty = product name.',
    f_metaDesc: 'Meta description',
    f_metaDesc_h: 'Empty = short description.',
    googlePreview: 'Search preview',
    inStock: 'In stock',
    c_status: 'Status',
    statusActiveH: 'Visible on the website and available to order.',
    statusDraftH: 'Hidden from the website until you activate it.',
    f_active: 'Active on site',
    f_featured: 'Featured product',
    f_featured_h: 'Shown in highlighted sections on the homepage.',
    translations: 'Translations',
    c_org: 'Organisation',
    f_category: 'Category',
    chooseCategory: 'Choose a category…',
    f_badges: 'Card badges',
    f_quote: 'Made to measure / price on request',
    f_quote_h: 'Customers request a quote instead of “Add to cart”.',
    c_stock: 'Inventory',
    f_sku: 'SKU',
    f_stock: 'Quantity in stock',
    f_mto: 'Made to order',
    f_mto_h: 'Produced to order — stock is not tracked.',
    lowStockWarn: 'Low stock — time to restock.',
    outOfStockWarn: 'Out of stock — shown as “made to order” on the website.',
    stockPacksH: 'Stock for m² products is counted in packs.',
    c_install: 'Installation',
    f_install: 'We offer installation',
    f_install_h: 'Customers can add installation in the cart.',
    f_installPrice: 'Installation price',
    c_delivery: 'Delivery & warranty',
    f_lead: 'Lead time',
    daysUnit: 'days',
    f_warranty: 'Warranty',
    yearsUnit: 'yrs',
    c_preview: 'Storefront preview',
    c_preview_d: 'The card updates as you type.',
    shortcutTip: 'Tip: Ctrl + S saves your changes.',
    e_name: 'Enter the Montenegrin name.',
    e_price: 'Price must be greater than 0.',
    e_category: 'Choose a category.',
    fixErrors: 'Please check the highlighted fields',
    created: 'Product created',
    saved: 'Changes saved',
    notFound: 'Product not found',
    notFoundText: 'It may have been deleted, or the link is not correct.',
    backToList: 'Back to products',
    leaveTitle: 'Leave without saving?',
    leaveText: 'Unsaved changes to this product will be lost.',
    leave: 'Leave',
  },
});
